### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by info247** [openredact/anonymizer#6]
The installation file produces an error.

**Comment by malteos** [comment]
Could you please provide the error message and details to your environment?

**Comment by Flow2908** [comment]
![Error Anonymizer](https://user-images.githubusercontent.com/86437281/148162235-9780c7b8-0e7b-4aa3-a9fb-1b13f1573bb4.PNG)

**Comment by Flow2908** [comment]
There are problems concerning the installation of the package anonymizer. Please give me the hint how can I resolve the error.

**Comment by langhabel** [comment]
I couldn't reproduce the error by installing with `pip install git+https://github.com/openredact/anonymizer.git#egg-anonymizer`. What pip version are you on? Could you try upgrade to the latest?

If that doesn't help, making the egg name match the package metadata should solve the issue:
`pip install git+https://github.com/openredact/anonymizer.git#egg-or-anonymizer`

**Comment by Flow2908** [comment]
> I couldn't reproduce the error by installing with `pip install git+https://github.com/openredact/anonymizer.git#egg-anonymizer`. What pip version are you on? Could you try upgrade to the latest?
> 
> If that doesn't help, making the egg name match the package metadata should solve the issue: `pip install git+https://github.com/openredact/anonymizer.git#egg-or-anonymizer`

I updated my pip version. It says "Requirement already satisfied: pip in /home/florian/.local/lib/python3.8/site-packages (21.3.1)"
Changing the egg name as indicated above doens't produce the same error message any more. However, it isnt't solved yet. Now, I get an error message that has the following last line:

 File "/home/florian/.local/lib/python3.8/site-packages/spacy/util.py", line 11, in <module>
    from thinc.api import NumpyOps, get_current_ops, Adam, Config, Optimizer
ImportError: cannot import name 'NumpyOps' from 'thinc.api' (/home/florian/.local/lib/python3.8/site-packages/thinc/api.py)

How can I fix the import error, please? Thank you for helping!

**Comment by langhabel** [comment]
Spacy and think aren't dependencies of this package. Please refer to thinc's documentation for usage instructions.
